### ISSUE TITLE
Sender From issue

### ISSUE THREAD

**Issue by asheesharyan** [smxi/php-html-mime-mail#1]
$sender = "Test< test@gmail.com >";
$mail->setFrom($sender);

In mail it is showing : Test <mymail@gmail.com>, i want to replace it by - test@gmail.com

**Comment by smxi** [comment]
Sorry, I forgot to put in the README that this project is not being maintained any more. 

However, a simple look at an example file shows that you did it wrong: $mail->setFrom('"Joe" <joe@example.com>');

**Comment by asheesharyan** [comment]
Sorry again , I am using smtp, I replaced, here is the code...
$mail->setFrom('"Joe" <joe@example.com>');

In mail it is showing- Joe <mygmail id>, And I want to replace mygmail id with joe@example.com.

Any solution or any suggestion?.....

**Comment by smxi** [comment]
No, sorry, I'm not offering support for this, but it's easy to debug such issues if you just echo out the data internally.
